package com.bgfang.material.entity.mapper;

import com.bgfang.material.condition.CustomerCondition;
import com.bgfang.material.entity.domain.CustomerDomain;
import com.bgfang.material.entity.vo.CustomerVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomerDomainMapper {

    List<CustomerVo> getListByPager(CustomerCondition condition);

    int getListCount(CustomerCondition condition);

    int updateDeleteStatus(@Param("id") String id, @Param("isDelete") boolean isDelete);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURTAINS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURTAINS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int insert(CustomerDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURTAINS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int insertSelective(CustomerDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURTAINS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    CustomerDomain selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURTAINS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int updateByPrimaryKeySelective(CustomerDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CURTAINS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int updateByPrimaryKey(CustomerDomain record);
}