package com.bgfang.material.entity.mapper;

import com.bgfang.material.entity.domain.FittingsDomian;

public interface FittingsDomianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FITTINGS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FITTINGS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int insert(FittingsDomian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FITTINGS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int insertSelective(FittingsDomian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FITTINGS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    FittingsDomian selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FITTINGS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int updateByPrimaryKeySelective(FittingsDomian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FITTINGS
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int updateByPrimaryKey(FittingsDomian record);
}