package com.bgfang.material.entity.mapper;

import com.bgfang.material.entity.domain.SupplierDomain;

public interface SupplierDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int insert(SupplierDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int insertSelective(SupplierDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    SupplierDomain selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int updateByPrimaryKeySelective(SupplierDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbggenerated Fri Apr 14 16:35:32 CST 2017
     */
    int updateByPrimaryKey(SupplierDomain record);
}