package com.bgfang.material.entity.domain;

import java.util.Date;

public class CurtainsDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.ID
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.NAME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.LENGTH
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Double length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.WIDTH
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Double width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.UNIT_PRICE
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Double unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.COUNT
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.VALUATION_METHOD
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Integer valuationMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.IMG_URL
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.REMARK
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.CREATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CURTAINS.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.ID
     *
     * @return the value of CURTAINS.ID
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.ID
     *
     * @param id the value for CURTAINS.ID
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.NAME
     *
     * @return the value of CURTAINS.NAME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.NAME
     *
     * @param name the value for CURTAINS.NAME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.LENGTH
     *
     * @return the value of CURTAINS.LENGTH
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Double getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.LENGTH
     *
     * @param length the value for CURTAINS.LENGTH
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setLength(Double length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.WIDTH
     *
     * @return the value of CURTAINS.WIDTH
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Double getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.WIDTH
     *
     * @param width the value for CURTAINS.WIDTH
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setWidth(Double width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.UNIT_PRICE
     *
     * @return the value of CURTAINS.UNIT_PRICE
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Double getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.UNIT_PRICE
     *
     * @param unitPrice the value for CURTAINS.UNIT_PRICE
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.COUNT
     *
     * @return the value of CURTAINS.COUNT
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.COUNT
     *
     * @param count the value for CURTAINS.COUNT
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.VALUATION_METHOD
     *
     * @return the value of CURTAINS.VALUATION_METHOD
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Integer getValuationMethod() {
        return valuationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.VALUATION_METHOD
     *
     * @param valuationMethod the value for CURTAINS.VALUATION_METHOD
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setValuationMethod(Integer valuationMethod) {
        this.valuationMethod = valuationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.IMG_URL
     *
     * @return the value of CURTAINS.IMG_URL
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.IMG_URL
     *
     * @param imgUrl the value for CURTAINS.IMG_URL
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.REMARK
     *
     * @return the value of CURTAINS.REMARK
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.REMARK
     *
     * @param remark the value for CURTAINS.REMARK
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.CREATE_TIME
     *
     * @return the value of CURTAINS.CREATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.CREATE_TIME
     *
     * @param createTime the value for CURTAINS.CREATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURTAINS.UPDATE_TIME
     *
     * @return the value of CURTAINS.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURTAINS.UPDATE_TIME
     *
     * @param updateTime the value for CURTAINS.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}