package com.bgfang.material.entity.domain;

import java.util.Date;

public class FittingsDomian {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FITTINGS.ID
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FITTINGS.NAME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FITTINGS.UNIT_PRICE
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Double unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FITTINGS.COUNT
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FITTINGS.REMARK
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FITTINGS.CREATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FITTINGS.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FITTINGS.ID
     *
     * @return the value of FITTINGS.ID
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FITTINGS.ID
     *
     * @param id the value for FITTINGS.ID
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FITTINGS.NAME
     *
     * @return the value of FITTINGS.NAME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FITTINGS.NAME
     *
     * @param name the value for FITTINGS.NAME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FITTINGS.UNIT_PRICE
     *
     * @return the value of FITTINGS.UNIT_PRICE
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Double getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FITTINGS.UNIT_PRICE
     *
     * @param unitPrice the value for FITTINGS.UNIT_PRICE
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FITTINGS.COUNT
     *
     * @return the value of FITTINGS.COUNT
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FITTINGS.COUNT
     *
     * @param count the value for FITTINGS.COUNT
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FITTINGS.REMARK
     *
     * @return the value of FITTINGS.REMARK
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FITTINGS.REMARK
     *
     * @param remark the value for FITTINGS.REMARK
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FITTINGS.CREATE_TIME
     *
     * @return the value of FITTINGS.CREATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FITTINGS.CREATE_TIME
     *
     * @param createTime the value for FITTINGS.CREATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FITTINGS.UPDATE_TIME
     *
     * @return the value of FITTINGS.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FITTINGS.UPDATE_TIME
     *
     * @param updateTime the value for FITTINGS.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}