package com.bgfang.material.entity.domain;

public class OrdersDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ORDER_PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private String orderProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ORDER_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.VALUATION_METHOD
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private Integer valuationMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.QUANTITY
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.PRODUCT_TYPE
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private Integer productType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ORDER_PRODUCT_ID
     *
     * @return the value of ORDERS.ORDER_PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public String getOrderProductId() {
        return orderProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ORDER_PRODUCT_ID
     *
     * @param orderProductId the value for ORDERS.ORDER_PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setOrderProductId(String orderProductId) {
        this.orderProductId = orderProductId == null ? null : orderProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ORDER_ID
     *
     * @return the value of ORDERS.ORDER_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ORDER_ID
     *
     * @param orderId the value for ORDERS.ORDER_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.PRODUCT_ID
     *
     * @return the value of ORDERS.PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.PRODUCT_ID
     *
     * @param productId the value for ORDERS.PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.VALUATION_METHOD
     *
     * @return the value of ORDERS.VALUATION_METHOD
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public Integer getValuationMethod() {
        return valuationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.VALUATION_METHOD
     *
     * @param valuationMethod the value for ORDERS.VALUATION_METHOD
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setValuationMethod(Integer valuationMethod) {
        this.valuationMethod = valuationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.QUANTITY
     *
     * @return the value of ORDERS.QUANTITY
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.QUANTITY
     *
     * @param quantity the value for ORDERS.QUANTITY
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.PRODUCT_TYPE
     *
     * @return the value of ORDERS.PRODUCT_TYPE
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.PRODUCT_TYPE
     *
     * @param productType the value for ORDERS.PRODUCT_TYPE
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }
}