package com.bgfang.material.entity.domain;

import java.util.Date;

public class OrderProductDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.ORDER_PRODUCT_ID
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    private String orderProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.VALUATION_METHOD
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    private Integer valuationMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.QUANTITY
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    private Double quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.IS_DELETE
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.CREATE_TIME
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.UPDATE_TIME
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.ORDER_PRODUCT_ID
     *
     * @return the value of ORDER_PRODUCT.ORDER_PRODUCT_ID
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public String getOrderProductId() {
        return orderProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.ORDER_PRODUCT_ID
     *
     * @param orderProductId the value for ORDER_PRODUCT.ORDER_PRODUCT_ID
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public void setOrderProductId(String orderProductId) {
        this.orderProductId = orderProductId == null ? null : orderProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.ORDER_ID
     *
     * @return the value of ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.ORDER_ID
     *
     * @param orderId the value for ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.PRODUCT_ID
     *
     * @return the value of ORDER_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.PRODUCT_ID
     *
     * @param productId the value for ORDER_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.VALUATION_METHOD
     *
     * @return the value of ORDER_PRODUCT.VALUATION_METHOD
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public Integer getValuationMethod() {
        return valuationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.VALUATION_METHOD
     *
     * @param valuationMethod the value for ORDER_PRODUCT.VALUATION_METHOD
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public void setValuationMethod(Integer valuationMethod) {
        this.valuationMethod = valuationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.QUANTITY
     *
     * @return the value of ORDER_PRODUCT.QUANTITY
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public Double getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.QUANTITY
     *
     * @param quantity the value for ORDER_PRODUCT.QUANTITY
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.IS_DELETE
     *
     * @return the value of ORDER_PRODUCT.IS_DELETE
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.IS_DELETE
     *
     * @param isDelete the value for ORDER_PRODUCT.IS_DELETE
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.CREATE_TIME
     *
     * @return the value of ORDER_PRODUCT.CREATE_TIME
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.CREATE_TIME
     *
     * @param createTime the value for ORDER_PRODUCT.CREATE_TIME
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.UPDATE_TIME
     *
     * @return the value of ORDER_PRODUCT.UPDATE_TIME
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.UPDATE_TIME
     *
     * @param updateTime the value for ORDER_PRODUCT.UPDATE_TIME
     *
     * @mbg.generated Fri Apr 28 21:43:51 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}