package com.bgfang.material.entity.domain;

public class OrderProductDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.ORDER_PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private String orderProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.VALUATION_METHOD
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private Integer valuationMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.COUNT
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_PRODUCT.PRODUCT_TYPE
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    private Integer productType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.ORDER_PRODUCT_ID
     *
     * @return the value of ORDER_PRODUCT.ORDER_PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public String getOrderProductId() {
        return orderProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.ORDER_PRODUCT_ID
     *
     * @param orderProductId the value for ORDER_PRODUCT.ORDER_PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setOrderProductId(String orderProductId) {
        this.orderProductId = orderProductId == null ? null : orderProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.ORDER_ID
     *
     * @return the value of ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.ORDER_ID
     *
     * @param orderId the value for ORDER_PRODUCT.ORDER_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.PRODUCT_ID
     *
     * @return the value of ORDER_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.PRODUCT_ID
     *
     * @param productId the value for ORDER_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.VALUATION_METHOD
     *
     * @return the value of ORDER_PRODUCT.VALUATION_METHOD
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public Integer getValuationMethod() {
        return valuationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.VALUATION_METHOD
     *
     * @param valuationMethod the value for ORDER_PRODUCT.VALUATION_METHOD
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setValuationMethod(Integer valuationMethod) {
        this.valuationMethod = valuationMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.COUNT
     *
     * @return the value of ORDER_PRODUCT.COUNT
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.COUNT
     *
     * @param count the value for ORDER_PRODUCT.COUNT
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_PRODUCT.PRODUCT_TYPE
     *
     * @return the value of ORDER_PRODUCT.PRODUCT_TYPE
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_PRODUCT.PRODUCT_TYPE
     *
     * @param productType the value for ORDER_PRODUCT.PRODUCT_TYPE
     *
     * @mbg.generated Thu Apr 20 19:13:19 CST 2017
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }
}