package com.bgfang.material.entity.domain;

import java.util.Date;

public class ProductDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.LENGTH
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private Double length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.WIDTH
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private Double width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PROPERTY
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private String property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.UNIT_PRICE
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private Double unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.TYPE
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.IMG_URL
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.REMARK
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.IS_DELETE
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CREATE_TIME
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.UPDATE_TIME
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_ID
     *
     * @return the value of PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCT_ID
     *
     * @param productId the value for PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_NAME
     *
     * @return the value of PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCT_NAME
     *
     * @param productName the value for PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.LENGTH
     *
     * @return the value of PRODUCT.LENGTH
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public Double getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.LENGTH
     *
     * @param length the value for PRODUCT.LENGTH
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setLength(Double length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.WIDTH
     *
     * @return the value of PRODUCT.WIDTH
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public Double getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.WIDTH
     *
     * @param width the value for PRODUCT.WIDTH
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setWidth(Double width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PROPERTY
     *
     * @return the value of PRODUCT.PROPERTY
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PROPERTY
     *
     * @param property the value for PRODUCT.PROPERTY
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.UNIT_PRICE
     *
     * @return the value of PRODUCT.UNIT_PRICE
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public Double getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.UNIT_PRICE
     *
     * @param unitPrice the value for PRODUCT.UNIT_PRICE
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.TYPE
     *
     * @return the value of PRODUCT.TYPE
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.TYPE
     *
     * @param type the value for PRODUCT.TYPE
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.IMG_URL
     *
     * @return the value of PRODUCT.IMG_URL
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.IMG_URL
     *
     * @param imgUrl the value for PRODUCT.IMG_URL
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.REMARK
     *
     * @return the value of PRODUCT.REMARK
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.REMARK
     *
     * @param remark the value for PRODUCT.REMARK
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.IS_DELETE
     *
     * @return the value of PRODUCT.IS_DELETE
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.IS_DELETE
     *
     * @param isDelete the value for PRODUCT.IS_DELETE
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.CREATE_TIME
     *
     * @return the value of PRODUCT.CREATE_TIME
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.CREATE_TIME
     *
     * @param createTime the value for PRODUCT.CREATE_TIME
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.UPDATE_TIME
     *
     * @return the value of PRODUCT.UPDATE_TIME
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.UPDATE_TIME
     *
     * @param updateTime the value for PRODUCT.UPDATE_TIME
     *
     * @mbg.generated Thu Apr 20 23:44:38 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}