package com.bgfang.material.entity.domain;

import java.util.Date;

public class SupplierDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.ID
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.NAME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.ADDRESS
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.TEL
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.PRODUCT
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.REMARK
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.CREATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.ID
     *
     * @return the value of SUPPLIER.ID
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.ID
     *
     * @param id the value for SUPPLIER.ID
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.NAME
     *
     * @return the value of SUPPLIER.NAME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.NAME
     *
     * @param name the value for SUPPLIER.NAME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.ADDRESS
     *
     * @return the value of SUPPLIER.ADDRESS
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.ADDRESS
     *
     * @param address the value for SUPPLIER.ADDRESS
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.TEL
     *
     * @return the value of SUPPLIER.TEL
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.TEL
     *
     * @param tel the value for SUPPLIER.TEL
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.PRODUCT
     *
     * @return the value of SUPPLIER.PRODUCT
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.PRODUCT
     *
     * @param product the value for SUPPLIER.PRODUCT
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.REMARK
     *
     * @return the value of SUPPLIER.REMARK
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.REMARK
     *
     * @param remark the value for SUPPLIER.REMARK
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.CREATE_TIME
     *
     * @return the value of SUPPLIER.CREATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.CREATE_TIME
     *
     * @param createTime the value for SUPPLIER.CREATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.UPDATE_TIME
     *
     * @return the value of SUPPLIER.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.UPDATE_TIME
     *
     * @param updateTime the value for SUPPLIER.UPDATE_TIME
     *
     * @mbggenerated Fri Apr 14 16:29:21 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}