package com.fang.material.entity.domain;

import java.util.Date;

public class OrdersDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ORDER_ID
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ORDER_NO
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.UPDATE_TIME
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.CUSTOMER_ID
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.SURVEY_DATE
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    private Date surveyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.INSTALLATION_DATE
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    private Date installationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.IS_DELETE
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.CREATE_TIME
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ORDER_ID
     *
     * @return the value of ORDERS.ORDER_ID
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ORDER_ID
     *
     * @param orderId the value for ORDERS.ORDER_ID
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ORDER_NO
     *
     * @return the value of ORDERS.ORDER_NO
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ORDER_NO
     *
     * @param orderNo the value for ORDERS.ORDER_NO
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.UPDATE_TIME
     *
     * @return the value of ORDERS.UPDATE_TIME
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.UPDATE_TIME
     *
     * @param updateTime the value for ORDERS.UPDATE_TIME
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.CUSTOMER_ID
     *
     * @return the value of ORDERS.CUSTOMER_ID
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.CUSTOMER_ID
     *
     * @param customerId the value for ORDERS.CUSTOMER_ID
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.SURVEY_DATE
     *
     * @return the value of ORDERS.SURVEY_DATE
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public Date getSurveyDate() {
        return surveyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.SURVEY_DATE
     *
     * @param surveyDate the value for ORDERS.SURVEY_DATE
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public void setSurveyDate(Date surveyDate) {
        this.surveyDate = surveyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.INSTALLATION_DATE
     *
     * @return the value of ORDERS.INSTALLATION_DATE
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public Date getInstallationDate() {
        return installationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.INSTALLATION_DATE
     *
     * @param installationDate the value for ORDERS.INSTALLATION_DATE
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public void setInstallationDate(Date installationDate) {
        this.installationDate = installationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.IS_DELETE
     *
     * @return the value of ORDERS.IS_DELETE
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.IS_DELETE
     *
     * @param isDelete the value for ORDERS.IS_DELETE
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.CREATE_TIME
     *
     * @return the value of ORDERS.CREATE_TIME
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.CREATE_TIME
     *
     * @param createTime the value for ORDERS.CREATE_TIME
     *
     * @mbg.generated Fri Apr 21 17:17:13 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}