package com.fang.material.entity.domain;

import java.util.Date;

public class UserDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USER_ID
     *
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USER_NAME
     *
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USER_FULL_NAME
     *
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    private String userFullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.PASSWD
     *
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.IS_DELETE
     *
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    private Boolean isDelete = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.CREATE_TIME
     *
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.USER_ID
     *
     * @return the value of USER.USER_ID
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.USER_ID
     *
     * @param userId the value for USER.USER_ID
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.USER_NAME
     *
     * @return the value of USER.USER_NAME
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.USER_NAME
     *
     * @param userName the value for USER.USER_NAME
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.USER_FULL_NAME
     *
     * @return the value of USER.USER_FULL_NAME
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public String getUserFullName() {
        return userFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.USER_FULL_NAME
     *
     * @param userFullName the value for USER.USER_FULL_NAME
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName == null ? null : userFullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.PASSWD
     *
     * @return the value of USER.PASSWD
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.PASSWD
     *
     * @param passwd the value for USER.PASSWD
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.IS_DELETE
     *
     * @return the value of USER.IS_DELETE
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.IS_DELETE
     *
     * @param isDelete the value for USER.IS_DELETE
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.CREATE_TIME
     *
     * @return the value of USER.CREATE_TIME
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.CREATE_TIME
     *
     * @param createTime the value for USER.CREATE_TIME
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.UPDATE_TIME
     *
     * @return the value of USER.UPDATE_TIME
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.UPDATE_TIME
     *
     * @param updateTime the value for USER.UPDATE_TIME
     * @mbg.generated Tue Apr 25 10:32:57 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}